version: '3'
services:
  backend:
    image: qnib/plain-influxdb:2.7.5
    platform: linux/amd64
    environment:
     - INFLUXDB_DATABASES=metrics
     - INFLUXDB_META_LOGGING=true
     - INFLUXDB_OPENTSDB_ENABLED=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 2003:2003
     - 4242:4242
     - 8086:8086
  prometheus:
    image: qnib/plain-prometheus:2.48.1
    ports:
      - "9099:9090"
    environment:
        STORAGE_REMOTE_WRITE: tasks.prometheus-storage-adapter:9201
        PROMETHEUS_STATIC_SCRAPE_LIST: dockerd:172.17.0.1:9323:/metrics,node1:192.168.99.100:9100:/metrics,node2:192.168.99.101:9100:/metrics,node3:192.168.99.102:9100:/metrics
        PROMETHEUS_DNS_SCRAPE_LIST: cadvisor:tasks.cadvisor:8080:/metrics
  telegraf:
    image: telegraf:1.27.4-alpine
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro telegraf
  chronograf:
    image: qnib/plain-chronograf:0.1.3.7@sha256:23cf1696820dc8c2d3dbb9d11388c8465d68d9256dd38ab5a4f1a38adf579128
    ports:
     - 8888:8888
    environment:
     - INFLUXDB_HOST=tasks.backend

  frontend:
    image: grafana/grafana-oss:10.2.3
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_HOST=tasks.backend
     - INFLUXDB_DB=metrics
